#!/bin/sh

. "`dirname $0`/lib/common.sh"

SIGNATURE="# !! generated by update-ssh-config.sh !! #"
TARGET="$HOME/.ssh/config"

if [ -e "$TARGET" ]; then
	grep "$SIGNATURE" "$TARGET" > /dev/null || {
		warn "The unmanaged .ssh/config file already exists."
		warn "update-ssh-config.sh will overwrite it. Is it okay?"
		echo -n "Hit ENTER to proceed, or Ctrl-C to cancel > "
		read
		if [ -e "$TARGET.backup"]; then
			fatal ".ssh/config.backup exists. Cannot create backup."
			exit 1
		fi
		mv "$TARGET" "$TARGET.backup" || {
			fatal "Couldn't create backup."
			exit 1
		}
		warn "Backup created at .ssh/config.backup."
	}
	notice "Updating the existing .ssh/config file."
else
	notice "Creating the .ssh/config file."
fi

echo "$SIGNATURE" > "$TARGET"
echo >> "$TARGET"

for INFILE in $({
	ls "$BASEDIR/private/ssh/config.d/"*.conf 2> /dev/null | sort
	ls "$BASEDIR/ssh/config.d/"*.conf 2> /dev/null | sort
}); do
	if [ -e "$INFILE" ]; then
		notice "Adding $INFILE"
		echo >> "$TARGET"
		echo "# -----------------------------" >>  "$TARGET"
		echo "# $INFILE" >>  "$TARGET"
		echo "# -----------------------------" >>  "$TARGET"
		echo >> "$TARGET"
		cat "$INFILE" >> "$TARGET"
	fi
done

